# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
name                     : &name "Jiaye Wu"
repository               : "jiaye-wu/jiaye-wu.github.io"
google_scholar_stats_use_cdn : True

